// <auto-generated />
using EGWebApplication3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGWebApplication3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231201054722_intialCreate")]
    partial class intialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EGWebApplication3.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Department = 2,
                            Email = "ram@gmail.com",
                            Name = "Ram"
                        },
                        new
                        {
                            Id = 5,
                            Department = 1,
                            Email = "ra@gmail.com",
                            Name = "Raj"
                        },
                        new
                        {
                            Id = 7,
                            Department = 1,
                            Email = "xyz@gmail.com",
                            Name = "xyz"
                        },
                        new
                        {
                            Id = 8,
                            Department = 1,
                            Email = "Tom@gmail.com",
                            Name = "Tom"
                        },
                        new
                        {
                            Id = 6,
                            Department = 1,
                            Email = "abc@gmail.com",
                            Name = "abc"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
